// Code generated by sqlc. DO NOT EDIT.

package data

import (
	"database/sql"
)

type Attendance struct {
	Userid sql.NullString
	Date   sql.NullString
}

type User struct {
	Userid sql.NullString
	Name   sql.NullString
	Data   sql.NullString
}
