// Code generated by sqlc. DO NOT EDIT.
// source: queries.sql

package data

import (
	"context"
)

const checkinUser = `-- name: CheckinUser :exec
INSERT INTO attendance (
  userid, date
) VALUES (
  ?, ?
)
`

type CheckinUserParams struct {
	Userid string
	Date   string
}

func (q *Queries) CheckinUser(ctx context.Context, arg CheckinUserParams) error {
	_, err := q.db.ExecContext(ctx, checkinUser, arg.Userid, arg.Date)
	return err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (
  userid, first_name, last_name, data
) VALUES (
  ?, ?, ?, ?
)
`

type CreateUserParams struct {
	Userid    string
	FirstName string
	LastName  string
	Data      string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.Userid,
		arg.FirstName,
		arg.LastName,
		arg.Data,
	)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
    WHERE userid = ?
`

func (q *Queries) DeleteUser(ctx context.Context, userid string) error {
	_, err := q.db.ExecContext(ctx, deleteUser, userid)
	return err
}

const getAttendance = `-- name: GetAttendance :many
SELECT attendance.userid, date, users.userid, first_name, last_name, data, hidden FROM attendance JOIN users ON users.userid=attendance.userid WHERE users.hidden = FALSE
`

type GetAttendanceRow struct {
	Userid    string
	Date      string
	Userid_2  string
	FirstName string
	LastName  string
	Data      string
	Hidden    int32
}

func (q *Queries) GetAttendance(ctx context.Context) ([]GetAttendanceRow, error) {
	rows, err := q.db.QueryContext(ctx, getAttendance)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAttendanceRow
	for rows.Next() {
		var i GetAttendanceRow
		if err := rows.Scan(
			&i.Userid,
			&i.Date,
			&i.Userid_2,
			&i.FirstName,
			&i.LastName,
			&i.Data,
			&i.Hidden,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMeetings = `-- name: GetMeetings :many
SELECT DISTINCT date FROM attendance
`

func (q *Queries) GetMeetings(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getMeetings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var date string
		if err := rows.Scan(&date); err != nil {
			return nil, err
		}
		items = append(items, date)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUser = `-- name: GetUser :one
SELECT userid, first_name, last_name, data, hidden FROM users
    WHERE userid = ? AND hidden = FALSE LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, userid string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, userid)
	var i User
	err := row.Scan(
		&i.Userid,
		&i.FirstName,
		&i.LastName,
		&i.Data,
		&i.Hidden,
	)
	return i, err
}

const getUserByName = `-- name: GetUserByName :one
SELECT count(*) FROM users
    WHERE first_name = ? AND last_name = ? AND hidden = FALSE LIMIT 1
`

type GetUserByNameParams struct {
	FirstName string
	LastName  string
}

func (q *Queries) GetUserByName(ctx context.Context, arg GetUserByNameParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getUserByName, arg.FirstName, arg.LastName)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const isUserCheckedIn = `-- name: IsUserCheckedIn :one
SELECT count(*) FROM attendance
    WHERE date = ? AND userid = ? AND hidden = FALSE
`

type IsUserCheckedInParams struct {
	Date   string
	Userid string
}

func (q *Queries) IsUserCheckedIn(ctx context.Context, arg IsUserCheckedInParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, isUserCheckedIn, arg.Date, arg.Userid)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listUsers = `-- name: ListUsers :many
SELECT userid, first_name, last_name, data, hidden FROM users
		WHERE  hidden = FALSE
    ORDER BY last_name
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.Userid,
			&i.FirstName,
			&i.LastName,
			&i.Data,
			&i.Hidden,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteUser = `-- name: SoftDeleteUser :exec
UPDATE users
		SET hidden = TRUE
    WHERE userid = ?
`

func (q *Queries) SoftDeleteUser(ctx context.Context, userid string) error {
	_, err := q.db.ExecContext(ctx, softDeleteUser, userid)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users SET first_name = ?, last_name = ?, data = ?
    WHERE userid = ?
`

type UpdateUserParams struct {
	FirstName string
	LastName  string
	Data      string
	Userid    string
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser,
		arg.FirstName,
		arg.LastName,
		arg.Data,
		arg.Userid,
	)
	return err
}

const updateUserIDinAttendance = `-- name: UpdateUserIDinAttendance :exec
UPDATE attendance
SET userid = ?
WHERE userid = ?
`

type UpdateUserIDinAttendanceParams struct {
	Userid   string
	Userid_2 string
}

func (q *Queries) UpdateUserIDinAttendance(ctx context.Context, arg UpdateUserIDinAttendanceParams) error {
	_, err := q.db.ExecContext(ctx, updateUserIDinAttendance, arg.Userid, arg.Userid_2)
	return err
}

const updateUserIDinUsers = `-- name: UpdateUserIDinUsers :exec
UPDATE users
SET userid = ?
WHERE userid = ?
`

type UpdateUserIDinUsersParams struct {
	Userid   string
	Userid_2 string
}

func (q *Queries) UpdateUserIDinUsers(ctx context.Context, arg UpdateUserIDinUsersParams) error {
	_, err := q.db.ExecContext(ctx, updateUserIDinUsers, arg.Userid, arg.Userid_2)
	return err
}

const userIDExists = `-- name: UserIDExists :one
SELECT count(*) FROM users
    WHERE userid = ? AND hidden = FALSE LIMIT 1
`

func (q *Queries) UserIDExists(ctx context.Context, userid string) (int64, error) {
	row := q.db.QueryRowContext(ctx, userIDExists, userid)
	var count int64
	err := row.Scan(&count)
	return count, err
}
