// Code generated by sqlc. DO NOT EDIT.

package data

type Attendance struct {
	Userid string
	Date   string
}

type User struct {
	Userid    string
	FirstName string
	LastName  string
	Data      string
}
